# Generated by Django 4.2.4 on 2023-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.IntegerField(blank=True, null=True, verbose_name='ключ'),
        ),
    ]
