# Generated by Django 4.2.4 on 2023-08-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='наименование')),
                ('product_description', models.TextField(verbose_name='описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение')),
                ('product_category', models.CharField(max_length=30, verbose_name='категория')),
                ('product_price', models.IntegerField(verbose_name='цена')),
                ('create_date', models.DateField(verbose_name='дата создания')),
                ('change_date', models.DateField(verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('product_name',),
            },
        ),
    ]
