# Generated by Django 4.2.4 on 2023-08-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='change_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата изменения'),
        ),
    ]
