# Generated by Django 4.2.4 on 2023-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_change_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('create_date', models.DateField(verbose_name='дата создания')),
                ('sign_publication', models.CharField(max_length=100, verbose_name='признак публикации')),
                ('count_views', models.IntegerField(verbose_name='количество просмотров')),
            ],
        ),
    ]
