# Generated by Django 4.2.4 on 2023-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_blog_options_alter_blog_count_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sign_publication',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
    ]
