# Generated by Django 4.2.4 on 2023-09-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
